require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc 'Start our app console'
task :console do
    Pry.start
end

desc 'Start our application'
task :run do
  cli = CLI.new
  cli.run
end
